### ISSUE TITLE
How many channels can be used in the control image?

### ISSUE THREAD

**Issue by sam598** [lllyasviel/ControlNet#10]
The [train documentation](https://github.com/lllyasviel/ControlNet/blob/main/docs/train.md) uses a single image for control. Even if the control is a black and white line image it seems to be a 3 channel RGB image.

Is it possible to use 4 or more channels (RGBA or concatenating multiple images) for control? Or is the 3 channel a limitation of the model?

**Comment by lllyasviel** [comment]
It is in https://github.com/lllyasviel/ControlNet/blob/main/cldm/cldm.py#L147
Perhaps a better idea is to add that to config file

**Comment by sam598** [comment]
Wonderful, thank you!
