### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by thibaudart** [lllyasviel/ControlNet#102]
I launched the tutorial_train and it's seems working well (epoch 0 and epoch 1 done). The generating image are ok!

But I don't find where/when the result model is saved.

**Comment by scarbain** [comment]
The model is saved at the end of every epochs in the lightning_logs folder > version_N

**Comment by thibaudart** [comment]
Thanks!

**Comment by shravankumar147** [comment]
> I launched the tutorial_train and it's seems working well (epoch 0 and epoch 1 done). The generating image are ok!
> 
> But I don't find where/when the result model is saved.

What's your GPU config, and how much time it took to finish the training @thibaudart ?
