### ISSUE TITLE
Add OpenPose Face Annotation Tool as an Option for Training ControlNet on Faces

### ISSUE THREAD

**Issue by northfoxz** [lllyasviel/ControlNet#107]
Hello,

I am using your repo to train ControlNet on faces, and I think it would be great to have the option to use OpenPose Face Annotation Tool for this purpose. OpenPose is a well-known and widely used tool for detecting and annotating key points on faces, and I believe that incorporating it into your repo would make it even more powerful and useful for face-related applications.

Would it be possible to add an option to use OpenPose Face Annotation Tool as an input to the ControlNet training process? This would allow us to take advantage of the rich features and capabilities of OpenPose for face detection and annotation, and improve the accuracy and robustness of the ControlNet model.

Thank you for considering my request, and please let me know if you have any questions or concerns.

Best regards,
Eddie

**Comment by gwyong** [comment]
Did you find how to add another condition?
