### ISSUE TITLE
Why is normalization of condition images and target images different?

### ISSUE THREAD

**Issue by sALTaccount** [lllyasviel/ControlNet#112]
When creating my own dataset based off of the dataset tutorial, I noticed that the source images and target images are normalized between different values

        # Normalize source images to [0, 1].
        source = source.astype(np.float32) / 255.0

        # Normalize target images to [-1, 1].
        target = (target.astype(np.float32) / 127.5) - 1.0

I couldn't find any information on why these are normalized differently in the paper or on github. Is this difference important?

**Comment by sALTaccount** [comment]
Oh, does this have to do with ReLU not being able to output negative values?

**Comment by sALTaccount** [comment]
https://github.com/lllyasviel/ControlNet/commit/330064db78c54b6a9710e883f1c885ffadc3f7c7
looks like it was purposefully changed to be this way recently

**Comment by xiankgx** [comment]
![image](https://user-images.githubusercontent.com/4113258/219986522-e3cc81c6-4c27-413a-bd48-9fda916c3616.png)

The new conditioning information (hint; edge maps; normal maps; etc) are encoded using a convnet Epsilon that is trained during training. There are 4 conv layers in this convnet and each layer reduces the spatial dimention of the feature map in half. This is done delibrerately so that the feature map is 1/16 of the image size. Since this is a separate network, it doesn't really matter if inputs are normalized to [0, 1] or [-1, +1], or [0, 255.0], it should still work.

**Comment by iLori-Jiang** [comment]
But then why the author modify the code separately if both ranges work?

> ![image](https://user-images.githubusercontent.com/4113258/219986522-e3cc81c6-4c27-413a-bd48-9fda916c3616.png)
> 
> The new conditioning information (hint; edge maps; normal maps; etc) are encoded using a convnet Epsilon that is trained during training. Since this is a separate network, it doesn't really matter if inputs are normalized to [0, 1] or [-1, +1], or [0, 255.0], it should still work.
> 
> Noticed that this network, code here: https://github.com/lllyasviel/ControlNet/blob/main/cldm/cldm.py#L146-L162
> 
> has 3 2d-conv layers with stride=2. Each of these conv layers reduce the spatial dimension of the input feature map in half. The combined effect of the entire model is to reduce the input feature map by a factor of 8 (=2 ** 3). This is consistent with the reduction factor of the VAE in SD (512 (image size) / 64 (latent feature map size) = 8).

**Comment by zhouyc98** [comment]
@sALTaccount  @iLori-Jiang   
I think it's related to the Stable Diffusion's output (note that ControlNet has the same architecture with SD). 

The output of SD (through VAE) is standard Gaussian distribution N(0,1). So I think normalizing the target image to the [-1, 1] will make the training easier, as the prediction and target have similar range. 

Ref: https://www.reddit.com/r/StableDiffusion/comments/15fbtj7/input_standardization_to_1_and_1_in_diffusion, https://datascience.stackexchange.com/questions/54296/should-input-images-be-normalized-to-1-to-1-or-0-to-1
