### ISSUE TITLE
About aspect reserved condition input

### ISSUE THREAD

**Issue by eeyrw** [lllyasviel/ControlNet#116]
When training SD a trick call aspect bucket will be used to keep raw aspect ratio of image by regulate input image size to 64x in width and height. This trick helps to avoid aggressive image crop and make SD more robust to different aspect ratio of image generation. So why don't ControlNet apply such kind of trick to condition image when training ControlNet?

**Comment by xiankgx** [comment]
Can you tell me more details about this trick?

**Comment by eeyrw** [comment]
@xiankgx Here: https://github.com/NovelAI/novelai-aspect-ratio-bucketing

**Comment by Mikubill** [comment]
I believe such trick already used in some models like s2p v5.

> Highly frequent unique samples are about 1M, Lowly frequent unique samples are about 7M. All state-of-the-art tricks are applied, like some data augmentations and aspect ratio bucketing. ([ref](https://github.com/lllyasviel/style2paints/tree/master/V5_preview))

**Comment by eeyrw** [comment]
It seems author are quite familiar with this trick. But according the [tutorial ](https://github.com/lllyasviel/ControlNet/blob/main/docs/train.md), it seems not using such kind of trick, but I am not sure if merely because of simplicity due to tutorial. Even in the paper said so:
![image](https://user-images.githubusercontent.com/2088817/219992051-1705e69e-594e-493b-995f-b6f7931f9df7.png)

**Comment by lllyasviel** [comment]
No. The 8 production-ready controlnets do not use aspect ratio bucketing. These model is trained to control Stability's models. Stability uses cropping other than aspect ratio bucketing.
