### ISSUE TITLE
where to download models?

### ISSUE THREAD

**Issue by tangjinou** [lllyasviel/ControlNet#124]
where to download models? like  **/models/control_sd15_canny.pth**

**Comment by ninjasaid2k** [comment]
Link: https://huggingface.co/lllyasviel/ControlNet/tree/main/models
There are pruned version that's only 700MBs, I let you know as soon as I find them.

**Comment by ydykid** [comment]
> Link: https://huggingface.co/lllyasviel/ControlNet/tree/main/models -> 5.71GB Link: https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main -> 723MB(Pruned)

why was it 502 when i opened them 😂

**Comment by ninjasaid2k** [comment]
> > Link: https://huggingface.co/lllyasviel/ControlNet/tree/main/models -> 5.71GB Link: https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main -> 723MB(Pruned)
> 
> why was it 502 when i opened them 😂

Really? I don't seem to have that error when I click on it. Must not be the link itself.

**Comment by paulszro** [comment]
> 

is there any difference between them in work?

**Comment by tangjinou** [comment]
> https://huggingface.co/lllyasviel/ControlNet/tree/main/models

已经测试OK

**Comment by wrf566** [comment]
> 

I have the same question，somebody can help us？thx

**Comment by wrf566** [comment]
> > Link: https://huggingface.co/lllyasviel/ControlNet/tree/main/models -> 5.71GB Link: https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main -> 723MB(Pruned)
> 
> is there any difference between them in work?

I have the same question，somebody can help us？thx

**Comment by TripleKiller666** [comment]
> 

Pruned usually for newer Graphic Cards only (that supports FP16) so you have reduced Memory requirement (Less VRAM used, sometimes slightly less accurate than normal Model)
