### ISSUE TITLE
Can not open http://0.0.0.0:7860

### ISSUE THREAD

**Issue by nanfang2000** [lllyasviel/ControlNet#125]
```
python gradio_canny2image.py
logging improved.
No module 'xformers'. Proceeding without it.
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loaded model config from [./models/cldm_v15.yaml]
Loaded state_dict from [./models/control_sd15_canny.pth]
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
```

It says to open local URL but I can not open http://0.0.0.0:7860

**Comment by Rlee719** [comment]
True setting 

block.launch(server_name='localhost')

**Comment by chky** [comment]
> Try setting
> 
> block.launch(server_name='localhost')

it works! thank you

**Comment by nanfang2000** [comment]
I get it work by setting 127.0.0.1, too.
Thanks @Rlee719 !

**Comment by eniora** [comment]
Sorry but where do I set this?

**Comment by Dharshan049** [comment]
sorry where to Try setting

block.launch(server_name='localhost')

**Comment by Wei-1989** [comment]
I modify the code in "gradio_fake_scribble2image.py" and "gradio_scribble2image.py". And it works.
if you use pycharm. try press double "shift" for quick search"block.launch"
