### ISSUE TITLE
How to modify the training steps using tutorial_train.py?

### ISSUE THREAD

**Issue by ariannaliu** [lllyasviel/ControlNet#134]
Thank you so much for the amazing work! I have one question related to the tutorial_train.py. 
I wonder if we can modify the total number of training steps and the number of epochs?
Thank you so much for your help

**Comment by lllyasviel** [comment]
see also https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html

**Comment by engrmusawarali** [comment]
@lllyasviel  Can you tell me, can we train controlnets on small datasets having samples 48.
