### ISSUE TITLE
[DOC] Tutorial for ControlNet in diffusers

### ISSUE THREAD

**Issue by haofanwang** [lllyasviel/ControlNet#137]
This tutorial (https://github.com/haofanwang/ControlNet-for-Diffusers) covers frequent questions about usage.

**(1)** How to replace the basemodel of ControlNet (this has already been supported in your repo). Instead of huggingface models, we also support satetensors format models.

**(2)** How to convert ConrolNet to diffusers framework supported format.

**(3)** How to support ControlNet with inpainting ability just like stable-diffusion-inpainting.

Hi, Lyumin @lllyasviel, if it is good to you, you can add it to Related Resources.

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/ControlNet/commit/0f926c1227d6fb34db0bc58205594caee917097c ok
