### ISSUE TITLE
correct procedure in case of more conditioning/control

### ISSUE THREAD

**Issue by batrlatom** [lllyasviel/ControlNet#14]
Hi, thank you for the code, it works flawlessly.
I have one question though... I am trying to add more control to the network so it can be controlled with two images instead of one. I am doing it in a way that I add 3 new channels to the control image and then dstack two images going to the training. Is it the right way or do you have any better approach in mind?

**Comment by lllyasviel** [comment]
should be correct. but training some complicated tasks will need relative large batchsize. so perhaps consider rent some a100 from clouds

**Comment by batrlatom** [comment]
thanks for the answer. And if I want to add more like class conditions instead of whole image, how should I proceed? For example ... I want to generate image based on the rotation of object and control is an angle of the rotation.

**Comment by lllyasviel** [comment]
draw bounding box

**Comment by batrlatom** [comment]
i will try it, thanks

**Comment by lzstudent** [comment]
> i will try it, thanks

Hi, did the training by stack work for you? Thanks

**Comment by VCBE123** [comment]
I would like to enhance the image's control further. However, when I replace the text CLIP encoder with a small fully connected network to embed the time sequence, represented by (T, value) pairs, the quality of the generated image significantly deteriorates. Do you have any advice on how to restore the full power of Controlnet for better results?

**Comment by XiangjiBU** [comment]
> Hi, thank you for the code, it works flawlessly. I have one question though... I am trying to add more control to the network so it can be controlled with two images instead of one. I am doing it in a way that I add 3 new channels to the control image and then dstack two images going to the training. Is it the right way or do you have any better approach in mind?

I also want to train on two control images, could you share where and how you add the code?
