### ISSUE TITLE
Not appearing in interface

### ISSUE THREAD

**Issue by Gibgezr** [lllyasviel/ControlNet#149]
Doesn't show up in the interface. Retried with a fresh install of Automatic1111, with Python 3.10.6 on Windows 10, everything works except this. The path it installs Controlnet to is different, it's just in a dir called "Controlnet" inside the extensions folder.
Was following the extremely simple instructions in this video: https://www.youtube.com/watch?v=g8EvT28b6MA

**Comment by morecatplease** [comment]
Also having this problem. Also tried a fresh install of Automatic1111. Everything appears to be fine and getting no errors, but ControlNet does not show up in the UI under the dice button on the img2img tab of Automatic1111.

**Comment by mikhailstasyuk** [comment]
Your question helped me, cause it actually contains the solution. We had to install the extension, not just ControlNet itself. 
This is the repo: https://github.com/Mikubill/sd-webui-controlnet

**Comment by Gibgezr** [comment]
Closing this, it's the unofficial tutorial video that is at issue, not this project.

**Comment by AbubkerDawood** [comment]
> Your question helped me, cause it actually contains the solution. We had to install the extension, not just ControlNet itself. This is the repo: https://github.com/Mikubill/sd-webui-controlnet

this acctully worked for me thank <3

**Comment by corvaloldoll** [comment]
same problem, last version of SD, but it still did not appear

**Comment by kianma42** [comment]
> same problem, last version of SD, but it still did not appear

try this
delete the Controlnet folder from your extensions. then after restarting Ui you have to do 2steps:
1.install it from url: paste https://github.com/lllyasviel/ControlNet.git
2.install it from available extensions. look for controlnet and install the one with 1200steps or more!

if not you have to reinstall the Stable diffusion  and try the 2steps again

(this is the way that I fixed my problem without coding)

**Comment by joeyjr** [comment]
> > same problem, last version of SD, but it still did not appear
> 
> try this delete the Controlnet folder from your extensions. then after restarting Ui you have to do 2steps: 1.install it from url: paste https://github.com/lllyasviel/ControlNet.git 2.install it from available extensions. look for controlnet and install the one with 1200steps or more!
> 
> if not you have to reinstall the Stable diffusion and try the 2steps again
> 
> (this is the way that I fixed my problem without coding)

this fixed it for me! Thank you so much for sharing this!

**Comment by eonkidta** [comment]
> > same problem, last version of SD, but it still did not appear
> 
> try this delete the Controlnet folder from your extensions. then after restarting Ui you have to do 2steps: 1.install it from url: paste https://github.com/lllyasviel/ControlNet.git 2.install it from available extensions. look for controlnet and install the one with 1200steps or more!
> 
> if not you have to reinstall the Stable diffusion and try the 2steps again
> 
> (this is the way that I fixed my problem without coding)

didnt got fixed for me while using transformers==4.19.2 but controlnet is visible with transformers==4.30.2
with transformers==4.30.2 SD is not working model is not loading
