### ISSUE TITLE
conda env create -f environment.yaml failure on Intel Core i7 MacPro, ResolvePackageNotFound

### ISSUE THREAD

**Issue by myBigbug** [lllyasviel/ControlNet#150]
How to choose cudatoolkit version？

**Comment by myBigbug** [comment]
https://pytorch.org/get-started/previous-versions/   version

**Comment by CGCooke** [comment]
I'm getting 
"Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3"

when I try to create the env on a Mac Mini M2.

**Comment by CGCooke** [comment]
This .env file works if you have an ARM64 based Apple computer: 
name: control
channels:
  - pytorch
  - defaults
dependencies:
  - python
  - pip
  - pytorch
  - torchvision
  - numpy
  - pip:
      - gradio
      - albumentations
      - opencv-contrib-python
      - imageio
      - imageio-ffmpeg
      - pytorch-lightning
      - omegaconf
      - test-tube>
      - streamlit
      - einops
      - transformers
      - webdataset
      - kornia
      - open_clip_torch
      - invisible-watermark
      - streamlit-drawable-canvas
      - torchmetrics
      - timm
      - addict
      - yapf
      - prettytable
      - safetensors
      - basicsr
