### ISSUE TITLE
Load trained model to produce an interactive interface.

### ISSUE THREAD

**Issue by Chasexj** [lllyasviel/ControlNet#212]
Thanks for the great work.
I followed your tutorial on "Train a ControlNet to Control SD" and reproduced the results, as well as a state dict saved under './models/control_sd15_ini.ckpt'.
I am wondering if you can provide a brief explanation on how to save/load the generated model and yield an interactive interface from it by running a script such as the 'gradio_canny2image.py'.
I tried replacing the line `model.load_state_dict(load_state_dict('./models/control_sd15_depth.pth', location='cuda'))` with `model.load_state_dict(load_state_dict('./models/control_sd15_ini.ckpt', location='cuda'))` but the outcome is not as expected.

**Comment by HassanBinHaroon** [comment]
@Chasexj Have you figured out the solution or are you getting expected outcome now? Kindly elaborate, Thanks!

**Comment by Chasexj** [comment]
I simply switched to stable diffusion webui and loaded the controlnet models there. > @Chasexj Have you figured out the solution or are you getting expected outcome now? Kindly elaborate, Thanks!

**Comment by HassanBinHaroon** [comment]
Thanks for the reply! 

I have trained the model on my custom dataset and I want to generate samples and do not require the UI at the moment. 

Can I have an online session with you so I can discuss in more detail?
