### ISSUE TITLE
No operator found for `memory_efficient_attention_backward`

### ISSUE THREAD

**Issue by MahdiMohseni0033** [lllyasviel/ControlNet#218]
when I wanted to train in fill50k , I was faced with following error , how can I address it?

NotImplementedError: No operator found for `memory_efficient_attention_backward` with inputs:
     query       : shape=(8, 1024, 1, 80) (torch.float32)
     key         : shape=(8, 77, 1, 80) (torch.float32)
     value       : shape=(8, 77, 1, 80) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattB` is not supported because:
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    requires a GPU with compute capability == 8.0 for 'query.shape[-1] > 64'
`cutlassB` is not supported because:
    Sm86 does not have enough shared-memory to run this kernel - see https://github.com/facebookresearch/xformers/issues/517
`smallkB` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 80

**Comment by MahdiMohseni0033** [comment]
> when I wanted to train in fill50k , I was faced with following error , how can I address it?
> 
> NotImplementedError: No operator found for `memory_efficient_attention_backward` with inputs: query : shape=(8, 1024, 1, 80) (torch.float32) key : shape=(8, 77, 1, 80) (torch.float32) value : shape=(8, 77, 1, 80) (torch.float32) attn_bias : <class 'NoneType'> p : 0.0 `flshattB` is not supported because: dtype=torch.float32 (supported: {torch.float16, torch.bfloat16}) requires a GPU with compute capability == 8.0 for 'query.shape[-1] > 64' `cutlassB` is not supported because: Sm86 does not have enough shared-memory to run this kernel - see [facebookresearch/xformers#517](https://github.com/facebookresearch/xformers/issues/517) `smallkB` is not supported because: max(query.shape[-1] != value.shape[-1]) > 32 unsupported embed per head: 80

I finally could solve this problem 
to addressing this problem , we should change precision from 32 to 16 ...

**Comment by off99555** [comment]
Did your training converge when you use float16 dtype? According to issue #265, it shouldn't converge.

**Comment by jingyangcarl** [comment]
I have the same issue

**Comment by jingyangcarl** [comment]
> I have the same issue

uninstall xformers solves my problem

**Comment by ysy31415** [comment]
I found simply upgrading xformers solves the issue. Works well with float32.
`pip install xformers==0.0.18`

**Comment by sibangde** [comment]
> I found simply upgrading xformers solves the issue. Works well with float32. `pip install xformers==0.0.18`

xformers==0.0.18 need pytorch > 2.0.0, but mine is 1.13, if I update the pytorch version, there may be more problems
