### ISSUE TITLE
How can I allow low_vram mode?

### ISSUE THREAD

**Issue by Lxr713** [lllyasviel/ControlNet#225]
I can run the gradio_canny2image.py without any issue.
But if the Image Resolution was been set to 512, the code send back an error.
I thought this issue might be cause by my GPU(Nvidia GeForce RTX 3060 Ti)'s 8GB vram is too low, It might be better if low_vram mode was allowed.
I don't know how to allow that mode, please help me, thanks

**Comment by SamStark-AW** [comment]
Documented here:
[https://github.com/lllyasviel/ControlNet/blob/main/docs/low_vram.md](url)

**Comment by Lxr713** [comment]
> 

thanks!
