### ISSUE TITLE
Not accurate when enter chinese prompt.

### ISSUE THREAD

**Issue by beautiful-boyyy** [lllyasviel/ControlNet#251]
Not accurate when enter chinese prompt.

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/66351806/224003121-826c54dd-ae72-4100-b635-4c71b4e628a7.png">

**Comment by rlabonte233** [comment]
Stable Diffusion is trained on English text - I am unsure if there are models that use Chinese text as input.
