### ISSUE TITLE
Runtime error while finetuning  Sizes of tensors must match except in dimension 1. Expected size 24 but got size 23

### ISSUE THREAD

**Issue by kernelguardian** [lllyasviel/ControlNet#259]
Error
`
line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "user/ControlNet/cldm/cldm.py", line 41, in forward
    h = torch.cat([h, hs.pop() + control.pop()], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 24 but got size 23 for tensor number 1 in the list.`

Was finetuning with source and target images of a dimensions 640x360.
Any thoughts?

**Comment by kernelguardian** [comment]
I fixed it by setting the width and height the same, so instead of 640x360 i used 512x512. Anyone know why it works? 😅

**Comment by yuchen-xiyue** [comment]
I have the same issue as yours. I tried to make inputs squared but it still exists. I finally solved it by using 512x512 resolution. I guess the one-pixel mismatch is due to different sampling in SD and ControlNet.

**Comment by HassanBinHaroon** [comment]
> I fixed it by setting the width and height the same, so instead of 640x360 i used 512x512. Anyone know why it works? 😅

I think image dimensions should be the multiple of 64.
