### ISSUE TITLE
Why the generated image is blurred

### ISSUE THREAD

**Issue by qingfengmingyue** [lllyasviel/ControlNet#264]
Why is the image generated by your own image very blurred, but the image in the project is very fine？
![image](https://user-images.githubusercontent.com/7944239/224629662-c1950f95-ff8c-4915-929b-4c78187c706a.png)

**Comment by qingfengmingyue** [comment]
@lllyasviel

**Comment by lllyasviel** [comment]
what images?

**Comment by qingfengmingyue** [comment]
> what images?

interior design pictures

**Comment by lllyasviel** [comment]
make sure that both the detector resolution and image resolution is 512, then generate multiple images, or dirctly use webui plugin where the results are often better

**Comment by lllyasviel** [comment]
This issue will be closed if no further conducts are given.
Feel free to provide images that could fail any models and we will take a look and reopen the issue.

**Comment by qingfengmingyue** [comment]
> This issue will be closed if no further conducts are given. Feel free to provide images that could fail any models and we will take a look and reopen the issue.

![image](https://user-images.githubusercontent.com/7944239/225259892-4a76cb89-6a3e-493a-a028-58d457deab7b.png)

**Comment by lllyasviel** [comment]
These are 16 non cherry picked results on a random run by me. Feel free to reopen the issue if you cannot achieve similar results:
![image](https://user-images.githubusercontent.com/19834515/225298385-c5a25a25-f68d-41d2-bbca-ee42fd2e0786.png)
If you think these results are still not sharp enough, feel free to search "high-res fix." in google or youtue to find more SD tutorials.

**Comment by qingfengmingyue** [comment]
> These are 16 non cherry picked results on a random run by me. Feel free to reopen the issue if you cannot achieve similar results: ![image](https://user-images.githubusercontent.com/19834515/225298385-c5a25a25-f68d-41d2-bbca-ee42fd2e0786.png) If you think these results are still not sharp enough, feel free to search "high-res fix." in google or youtue to find more SD tutorials.

Thank you very much for your reply，It’s amazing, are you also using the canny mode?

**Comment by lllyasviel** [comment]
If you cannot achieve results like this, try a fresh install of webui or this repo and post your detailed parameters.

**Comment by qingfengmingyue** [comment]
> Yes it is Canny model default parameters. If you cannot achieve results like this, try a fresh install of webui or this repo and post your detailed parameters.
That's strange, I also use the default parameters  and execute
python gradio_canny2image.py

**Comment by qingfengmingyue** [comment]
> Yes it is Canny model default parameters. If you cannot achieve results like this, try a fresh install of webui or this repo and post your detailed parameters.

That's strange, I also use the default parameters and execute
python gradio_canny2image.py

**Comment by lllyasviel** [comment]
can you reproduce this
![image](https://user-images.githubusercontent.com/19834515/225313461-ed367c79-2b2a-4150-a351-d6081530c810.png)

**Comment by qingfengmingyue** [comment]
> can you reproduce this ![image](https://user-images.githubusercontent.com/19834515/225313461-ed367c79-2b2a-4150-a351-d6081530c810.png)

The same result as yours appeared, but it is still not as high-definition as the image in your project. Is it because of the training data?

**Comment by lllyasviel** [comment]
this project use ddim as a baseline. you need to use webui plugin to get industrial-level results. webui plugin also support high res fix.

**Comment by qingfengmingyue** [comment]
> this project use ddim as a baseline. you need to use webui plugin to get industrial-level results. webui plugin also support high res fix.

Got it, thank you very much
