### ISSUE TITLE
Training doesn't converge after 12000 steps

### ISSUE THREAD

**Issue by jamesWalker55** [lllyasviel/ControlNet#265]
Hi, thanks for your amazing work.

I'm trying to train the `fill50k` tutorial dataset. However, after training for 12000 steps, the model still does not converge.

![image](https://user-images.githubusercontent.com/30405220/224682525-703e0cbd-2a5e-4ee9-8565-9319ca0e47be.png)

I am training this locally on my desktop. To make the training script work, I've made the following changes to `tutorial_train.py`:

```diff
diff --git a/cldm/logger.py b/cldm/logger.py
index 6a88038..d092480 100644
--- a/cldm/logger.py
+++ b/cldm/logger.py
@@ -71,6 +71,6 @@ class ImageLogger(Callback):
     def check_frequency(self, check_idx):
         return check_idx % self.batch_freq == 0
 
-    def on_train_batch_end(self, trainer, pl_module, outputs, batch, batch_idx, dataloader_idx):
+    def on_train_batch_end(self, trainer, pl_module, outputs, batch, batch_idx):
         if not self.disabled:
             self.log_img(pl_module, batch, batch_idx, split="train")
diff --git a/ldm/models/diffusion/ddpm.py b/ldm/models/diffusion/ddpm.py
index f71a44a..50df5a4 100644
--- a/ldm/models/diffusion/ddpm.py
+++ b/ldm/models/diffusion/ddpm.py
@@ -588,7 +588,7 @@ class LatentDiffusion(DDPM):
 
     @rank_zero_only
     @torch.no_grad()
-    def on_train_batch_start(self, batch, batch_idx, dataloader_idx):
+    def on_train_batch_start(self, batch, batch_idx):
         # only for very first batch
         if self.scale_by_std and self.current_epoch == 0 and self.global_step == 0 and batch_idx == 0 and not self.restarted_from_ckpt:
             assert self.scale_factor == 1., 'rather not use custom rescaling and std-rescaling simultaneously'
diff --git a/tutorial_train.py b/tutorial_train.py
index 393d7ad..76eb3a8 100644
--- a/tutorial_train.py
+++ b/tutorial_train.py
@@ -8,7 +8,7 @@ from cldm.model import create_model, load_state_dict
 
 
 # Configs
-resume_path = './models/control_sd15_ini.ckpt'
+resume_path = './models/ctl-sd15.ckpt'
 batch_size = 4
 logger_freq = 300
 learning_rate = 1e-5
@@ -28,7 +28,7 @@ model.only_mid_control = only_mid_control
 dataset = MyDataset()
 dataloader = DataLoader(dataset, num_workers=0, batch_size=batch_size, shuffle=True)
 logger = ImageLogger(batch_frequency=logger_freq)
-trainer = pl.Trainer(gpus=1, precision=32, callbacks=[logger])
+trainer = pl.Trainer(gpus=1, precision=16, callbacks=[logger])
 
 
 # Train!
```

The model I used was the **`v1-5-pruned-emaonly.ckpt`** model, which is different from the `v1-5-pruned.ckpt` model specified in the [tutorial document](https://github.com/lllyasviel/ControlNet/blob/main/docs/train.md).

However, from these changes alone I don't understand why the training has failed. What could be the reason for this failure?

**Comment by yifangao112** [comment]
Same problem. The model I used was `v1-5-pruned.ckpt`, but still does not converge after 16K steps. My training code is different from the `tutorial_train.py` only for `precision=16` in order to use xformers.

**Comment by lllyasviel** [comment]
SD seems to hate precision=16, many LoRA trainings also fail when precision=16

**Comment by jamesWalker55** [comment]
> SD seems to hate precision=16, many LoRA trainings also fail when precision=16

Can confirm. After switching to `precision=32`, my training converged at around 7500 steps:

![image](https://user-images.githubusercontent.com/30405220/224862552-e54df028-a119-4caf-998d-5ccbec00ca3c.png)

**Comment by HassanBinHaroon** [comment]
@yifangao112 Is [v1-5-pruned.ckpt](https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main) still available? I am unable to open the link. 

Can you please send the v1-5-pruned.ckpt?

**Comment by HassanBinHaroon** [comment]
@lllyasviel @jamesWalker55 @yifangao112 @scarbain @williamyang1991 

By steps, Do you mean global steps (that is printed in the log)?

**Comment by AlanZhang1995** [comment]
> > SD seems to hate precision=16, many LoRA trainings also fail when precision=16
> 
> Can confirm. After switching to `precision=32`, my training converged at around 7500 steps:
> 
> ![image](https://user-images.githubusercontent.com/30405220/224862552-e54df028-a119-4caf-998d-5ccbec00ca3c.png)

Sorry for bothering. But I find that, in your screenshot, the color of sample is quite different from that of reconstruction. Why could we conclude it as convergent?
