### ISSUE TITLE
Why are the pictures generated by pre-trained model is very blurry?

### ISSUE THREAD

**Issue by qingfengmingyue** [lllyasviel/ControlNet#278]
https://huggingface.co/spaces/hysts/ControlNet

![image](https://user-images.githubusercontent.com/7944239/225261403-9ce12cf6-9dfd-4f9e-9447-a15762c63ec2.png)

**Comment by lllyasviel** [comment]
do not use canny detector to detect edge maps of edges again. you can directly use canny or scribble model to process image. feel free to use webui plugin to achieve that.
