### ISSUE TITLE
control depth clipping in image log

### ISSUE THREAD

**Issue by sam598** [lllyasviel/ControlNet#28]
I am training a custom control model using depth maps. In the image log all of the "control images" are being saved with the lower half of color values (less than 128 from the .png, less than 0.0 in torch space) clipped to black.

In this example the left is the source depth map, and the right is the output "control image" log.
![depth_clipping_example](https://user-images.githubusercontent.com/10446449/218345886-e7637d5c-baf7-4d40-aca4-b01b3685d83f.png)

All of the color images (reconstruction and sample) come out as proper full color images.

Is this just a bug in how log images are saved? Or is there something wrong with how the control images are being converted for training?

I am using the provided unmodified `tutorial_dataset.py` and `tutorial_train.py` scripts.

**Comment by lllyasviel** [comment]
oh god it seems that image log is in space [0, 1] but tutorial_dataset.py is in space [-1,1]. will fix asap

**Comment by lllyasviel** [comment]
Fixed.
https://github.com/lllyasviel/ControlNet/commit/330064db78c54b6a9710e883f1c885ffadc3f7c7

**Comment by sam598** [comment]
No worries. This is only the log right, it does not affect training?

**Comment by lllyasviel** [comment]
for control image, using [0, 1] is better because in many cases like edge maps, 0 can be bg while edges can be 1. It you do not pull then it does not influence training

**Comment by sam598** [comment]
It looks like in the data loader the target image is still mapped in the -1.0 to 1.0 range.

Wouldn’t it make sense for the control image to be in the same color range as well?

**Comment by lllyasviel** [comment]
target image must use same space as SD. control image better to use [0, 1] as many app use edge maps

**Comment by sam598** [comment]
Why would a minimum value of 0.0 be better for edge maps? Wouldn’t it be better if the background is -1.0, so that it gives a greater distance between the edge and background values, while also keeping it in the same color space as SD.

**Comment by sam598** [comment]
Normal maps are also traditionally in a -1.0 to 1.0 range. Mapping the range to what is normally used isn’t really a valid reason since there are use cases for both. The range should be whatever trains the best.

**Comment by basit-MT** [comment]
Hi @lllyasviel, could you tell more about the depth maps used for training? 

1. Which MiDaS model was used?
2. Did you use inverted depth maps? (higher values for closer, smaller for far)
3. Did you normalize depths from 0-1 for training?

would really appreciate a response.
