### ISSUE TITLE
What's the purpose the add-minus operation of the original sd weight when loading controlnet weights?

### ISSUE THREAD

**Issue by feiyangsuo** [lllyasviel/ControlNet#282]
https://github.com/Mikubill/sd-webui-controlnet/blob/6e339e9b578019576155e7902c660fb88acdcb36/scripts/cldm.py#L93
This line add `unet_state_dict[key_name].clone().cpu()` then minus `state_dict["model.diffusion_model."+key_name]`, which, to my knowledge, should be having the same value. If so, why not just use `p_new = p` for simple? Or is my understanding wrong?

**Comment by lllyasviel** [comment]
This is related to an obsolete method https://github.com/lllyasviel/ControlNet/discussions/12
