### ISSUE TITLE
How to use a trained model

### ISSUE THREAD

**Issue by LiuShiyu95** [lllyasviel/ControlNet#283]
Thanks for the fantastic work! I would like to ask a question.
After I have trained the model using my own data, how should I use the model？
I'm trying to modify the video provided by you_ The pose2image.py code generates images, but the results differ significantly from the log printed during training.
Is there any error in this part of the code?
Thanks again for your work!
`       

        model.control_scales = [strength] * 13
        samples, intermediates = ddim_sampler.sample(ddim_steps, num_samples,
                                                     shape, cond, verbose=False, eta=eta,
                                                     unconditional_guidance_scale=scale,
                                                     unconditional_conditioning=un_cond)

        if config.save_memory:
            model.low_vram_shift(is_diffusing=False)

        x_samples = model.decode_first_stage(samples)
        x_samples = (einops.rearrange(x_samples, 'b c h w -> b h w c') * 127.5 + 127.5).cpu().numpy().clip(0, 255).astype(np.uint8)
        results = [x_samples[i] for i in range(num_samples)]
    return [detected_map] + results
`

**Comment by LiuShiyu95** [comment]
s

**Comment by mahdip72** [comment]
@LiuShiyu95 
I have the same problem. What should I do?

**Comment by HassanBinHaroon** [comment]
Kindly elaborate, How to use your own trained model?

**Comment by HassanBinHaroon** [comment]
@LiuShiyu95 Did you figure out any clue? Kindly share here if yes. Thanks!

**Comment by LiuShiyu95** [comment]
> @LiuShiyu95 I have the same problem. What should I do?
I'm  sorry I just saw the message. You can refer to the author's gradio_pose2image.py code. After nomalizing the photos, follow the process.

**Comment by LiuShiyu95** [comment]
> @LiuShiyu95 Did you figure out any clue? Kindly share here if yes. Thanks!
You can refer to the author's gradio_pose2image.py code. After nomalizing the photos, follow the process.

**Comment by WHUEugene** [comment]
我也觉得训练后进行推理的部分和日志里面相差甚远，我觉得这是一个很严重的为你
