### ISSUE TITLE
Tensor size mismatch when using custom image dataset

### ISSUE THREAD

**Issue by SwayStar123** [lllyasviel/ControlNet#288]
I tried making the images 1:1 square too, didnt work

I get this error

File "ControlNet\cldm\cldm.py", line 296, in forward
    h += guided_hint
RuntimeError: The size of tensor a (34) must match the size of tensor b (35) at non-singleton dimension 2

With the numbers 34 and 35 changing everytime. (Because its shuffling dataset)

If I replace my dataset with the fill50k dataset, then it works fine.  Both the hint and target images are the same resolution at 270x270. Am I missing something?

**Comment by SwayStar123** [comment]
The tutorial_test_dataset works fine and shows both images as having the same shape

**Comment by cccpocker** [comment]
@SwayStar123  I have the same problem? how did you solve it?

**Comment by SwayStar123** [comment]
I think I rounded all my images to nearest 64 on both axis and that solved it

**Comment by gg-yunse** [comment]
I reshaped my images to have size (270, 270, 3) but am still having an issue. What does it mean to round it to nearest 64

**Comment by SwayStar123** [comment]
@gg-yunse I meant the nearest multiple of 64, like 128, 192, 256, 320, and so on

**Comment by Abhishek0075** [comment]
does the images need to be of the square shape ie same height and width
