### ISSUE TITLE
It's interesting that you accumulate `h` here

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [lllyasviel/ControlNet#298]
Hey, guys, it's interesting that  you accumulate the `h` here ? Any insights?

https://github.com/lllyasviel/ControlNet/blob/16ea3b5379c1e78a4bc8e3fc9cae8d65c42511b1/cldm/cldm.py#L296

**Comment by YihanHu-2022** [comment]
![image](https://user-images.githubusercontent.com/58056486/228758839-8914664f-2b17-4c85-9b79-574294d0ba4c.png)
The h here corresponds to the input feature in the figure, and the sum operation here corresponds to the red box area in the figure. In fact, this step is only performed once (refer to the conditional branch judgment condition here in the code). But I still have a question whether the order of lines 295 and 296 is reversed.

**Comment by Zhaoyi-Yan** [comment]
Thank you for your explanation, very clear!
