### ISSUE TITLE
Why was the result so terrible? 

### ISSUE THREAD

**Issue by My12123** [lllyasviel/ControlNet#36]
![2023-02-13_16-38-23](https://user-images.githubusercontent.com/49092250/218473029-6515f781-5f7c-482e-9954-254806ce6005.png)
![huggingface co_spaces_RamAnanth1_ControlNet(Nest Hub Max)](https://user-images.githubusercontent.com/49092250/218473567-cc7afe30-b9a3-4e47-9cda-0c97c7ab79e3.png)

**Comment by lllyasviel** [comment]
look at the resolution. it is 300
