### ISSUE TITLE
GPU memory for depth-based model

### ISSUE THREAD

**Issue by Crane-YU** [lllyasviel/ControlNet#375]
Hi @lllyasviel,
Thx for sharing the work. just wondering how much memory space is required for depth model. I got RTX3090 for 24 GB and I always get oom issue. I turned save_memory to true with input image of size 512x512.

**Comment by lllyasviel** [comment]
this repo require at least 8gb vram. a1111 ControlNet requires at least 4 gb vram. if cannot use it for with 24g, then the setting is likely wrong.

**Comment by Crane-YU** [comment]
Thx for the reply, I just found it was because my gpu error.

**Comment by feifeitu1** [comment]
hello，please tell me what's wrong with RTX3090，I meet the same problem.
