### ISSUE TITLE
question about the role of "feature addition" in controlnet

### ISSUE THREAD

**Issue by girafffeee** [lllyasviel/ControlNet#390]
Hi, thanks for the great work. 
![image](https://user-images.githubusercontent.com/15151539/236615084-8abf4a7e-067f-460b-97c8-25a90af59df4.png)
Could you explain the role of "feature addition" ? What if the "input" is not added to condition branch?
I was quite confused but I didn't see any explanation or ablation in your paper. 
Thanks.

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/ControlNet/discussions/216
