### ISSUE TITLE
Custom SD model without extra trainingset

### ISSUE THREAD

**Issue by prometx11** [lllyasviel/ControlNet#4]
Is it possible to apply this method to a custom SD (1.5) model without using a dedicated training set? 
I would like to use your ControlNet + the canny edge detection but with a custom fine-tuned SD 1.5 model. 
Is that possible without using a training set? 
If not, how would one get a model with the canny edge detection, what dataset would you use? Generating the dataset with the annotator (like in gradio_annotator.py)?

Thanks a lot and keep up this amazing work!

**Comment by lllyasviel** [comment]
perhaps i can provide a script to do something like novelai_controlnet=novelai+sd15controlnet-sd15. let me try this weekend

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: prometx11 ***@***.***>
Sent: Saturday, February 11, 2023 9:46:13 AM
To: lllyasviel/ControlNet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lllyasviel/ControlNet] Custom SD model without extra trainingset (Issue #4)


Is it possible to apply this method to a custom SD (1.5) model without using a dedicated training set?
I would like to use your ControlNet + the canny edge detection but with a custom fine-tuned SD 1.5 model.
Is that possible without using a training set?
If not, how would one get a model with the canny edge detection, what dataset would you use? Generating the dataset with the annotator (like in gradio_annotator.py)?

Thanks a lot and keep up this amazing work!

―

**Comment by ExponentialML** [comment]
For the time being, if you have the AUTOMATIC webui installed, you can do a checkpoint merge.

- Simply rename the `pth` to `ckpt`, copy it in where your model directory is, then go to the Checkpoint Merge tab. 
- Choose the control model as A, your model as B, and the SD1.5 model as C. 
- Then, just set the alpha weight to 1 to get your model's layers. 

When merging, the `control_model` layers will simply be ignored, and only the SD1.5 layer weights will be updated. This will work for now until an official script for this repo is implemented.

**Comment by lllyasviel** [comment]
Done. See https://github.com/lllyasviel/ControlNet/discussions/12

**Comment by toyxyz** [comment]
> For the time being, if you have the AUTOMATIC webui installed, you can do a checkpoint merge.
> 
> * Simply rename the `pth` to `ckpt`, copy it in where your model directory is, then go to the Checkpoint Merge tab.
> * Choose the control model as A, your model as B, and the SD1.5 model as C.
> * Then, just set the alpha weight to 1 to get your model's layers.
> 
> When merging, the `control_model` layers will simply be ignored, and only the SD1.5 layer weights will be updated. This will work for now until an official script for this repo is implemented.

I merged Nai with control_sd15_openpose using Automatic webui.
![image](https://user-images.githubusercontent.com/8006000/218298511-9ab16ca6-4c49-46b0-b4eb-f63c869896d0.png)
