### ISSUE TITLE
Openpose doesn't understand the difference between the front and the back.

### ISSUE THREAD

**Issue by alexblattner** [lllyasviel/ControlNet#406]
Hey, Illyasviel. Your model is insanely good, however it has an issue distinguishing between the back and the front. If I want to see the back of a character, it will tend to show me the front. It is not an issue right now, but it would take this to the next level if it also took the back into account

**Comment by alexblattner** [comment]
> try adding prompts like "from front", "from back".

that's something I would like to avoid if possible because it isn't consistent and there's in between situations

> if not you can try the extension "posex" which will let you use a camera to rotate around the stick figure

it won't work

thanks for trying to help @dilectiogames , but in this case, it's a model training issue

**Comment by lllyasviel** [comment]
note that left shoulder is red and right shoulder is orange
if person in back, remember to use orange left and red right

**Comment by alexblattner** [comment]
@lllyasviel thanks for answering, but I have tried that. The model feels inconsistent when it comes to the back and favors the front for some reason

**Comment by alexblattner** [comment]
@lllyasviel I found the way to do tell it if it's the back or not. I should have hidden the eyes and the nose. it is 100% consistent from my 10 tries

**Comment by fafayqa** [comment]
> [@lllyasviel](https://github.com/lllyasviel) I found the way to do tell it if it's the back or not. I should have hidden the eyes and the nose. it is 100% consistent from my 10 tries

Here we go in May 2025 and it STILL HAS A PROBLEM RCOGNIZING BACK /FRONT despite me using your suggested "trick" of masking the eyes and nose in the controlnet image...it still renders as front view despite the trick and despite the prompt with (((seen from behind:1.5)))
