### ISSUE TITLE
ControlNet tab is missing

### ISSUE THREAD

**Issue by AndreyDonchev** [lllyasviel/ControlNet#481]
Hi. After installing ControlNet from the url in this depository, the ControlNet tab in the interface of Automatic1111 is missing.  I restarted several times, both from the program and the program itself. It is in the list of the installed extensions, but not in the  interface of the A1111. Could I reinstall it? How?

**Comment by JosefKuchar** [comment]
This is not WebUI controlnet extension repository, it's the core, make the report on https://github.com/Mikubill/sd-webui-controlnet if you think there is a bug
