### ISSUE TITLE
[Feature] Support SDXL 1.0

### ISSUE THREAD

**Issue by SpenserCai** [lllyasviel/ControlNet#485]
[SDXL 1.0](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0) is update,can support SDXL 1.0 ?

**Comment by tengshaofeng** [comment]
looking forward that.

**Comment by Michaelvirga** [comment]
Any updates on this? Roadmap / plan? @lllyasviel

**Comment by navalguijo** [comment]
I remember Emad saying a month ago that SDXL was ready for ComfyUI and ready for controlnet...what is the problem?

**Comment by geroldmeisinger** [comment]
use HuggingFace Diffuser's training script https://github.com/huggingface/diffusers/blob/main/examples/controlnet/README_sdxl.md

**Comment by geroldmeisinger** [comment]
duplicate: https://github.com/lllyasviel/ControlNet/issues/461

**Comment by SpenserCai** [comment]
complete
