### ISSUE TITLE
img2img Batch error

### ISSUE THREAD

**Issue by thargal** [lllyasviel/ControlNet#56]
Hi,
When I try to run the batch I have this error after the first image :
AttributeError: 'numpy.ndarray' object has no attribute 'save'

I think it try to save the second image (sketch) but don't find the save information.

Can you help me ?
Thanks

**Comment by jalexander831** [comment]
Would love additional support as this is the same error I have as well. I'm guessing it just wasn't programed to work with batch img2img yet but figured i'd give this request some love.

**Comment by nakaleo** [comment]
Hi, I am facing the same issue when running a batch in img2img:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui\modules\img2img.py", line 163, in img2img
    process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args)
  File "C:\stable-diffusion-webui\modules\img2img.py", line 76, in process_batch
    processed_image.save(os.path.join(output_dir, filename))
AttributeError: 'numpy.ndarray' object has no attribute 'save'

**Comment by thargal** [comment]
hello, i find a solution !
I delete all cache about huggingface (c:\users\your_name\.cache\huggingface something like this) and restart stable diffusion.
after that I found a new section CONTROLNET in the stable diffusion’s settings :-) so you need to uncheck the last option. after that it’s working very well :-D

**Comment by nakaleo** [comment]
> 
THank you for sharing
although it did't work for me. Still getting the same error.

**Comment by lllyasviel** [comment]
please move this to that webui repo

**Comment by nakaleo** [comment]
why? since it is a bug when controlnet is enabled
