### ISSUE TITLE
[question] restoring quality of a blurred screenshot

### ISSUE THREAD

**Issue by madrooky** [lllyasviel/ControlNet#564]
I hope it is OK to ask such a question here.

I want to restore/improve some pictures of a fictional person from a movie. I have already done a lot of manual work and trained a model with it. But with the source pictures the result becomes artificial looking. Very good actually but like plastic.
The person has some very distinct facial features. Control net so far seem to be promising to rework my data set to get a realistic likeness. However i keep losing details over iterations.
I basically only need to sharpen the images and get the skin details without touching the shapes. But with some images i am losing my mind, I keep losing the outlines of the nose and chin shape for example.
I am working with lowest cfg, low denoising, and have tried all the CN models.

InstructP2P and NormalMap seem to be promising but both fail in different aspects. 
With Instruct the shape remains untouched but it completely ruins the skin texture and adds noisy fragments that look like dirt and it gets worse and worse. 
NomalMap makes the good textures but i am losing the shapes.

What is a good way to combine the good qualities of both models? 

Or is there another way someone can recommend?

Thanks!

**Comment by geroldmeisinger** [comment]
> I hope it is OK to ask such a question here.

you are in "issues", a better fit would be "discussions", but nvm

try the "Tile" controlnet
btw: if you want better help you should provide more details. "trained a model", finetune? lora? how many pictures? parameters? provide pictures of your screenshots, and the results with each CN. what does plastic look like? are you using SD1, 2, XL?  etc.

**Comment by madrooky** [comment]
> > I hope it is OK to ask such a question here.
> 
> you are in "issues", a better fit would be "discussions", but nvm
> 
> try the "Tile" controlnet btw: if you want better help you should provide more details. "trained a model", finetune? lora? how many pictures? parameters? provide pictures of your screenshots, and the results with each CN. what does plastic look like? are you using SD1, 2, XL? etc.

OK yeah, gonna repost it in discussions then. Don't know why i did not think so far...^^ Thanks :)
