### ISSUE TITLE
Feature idea

### ISSUE THREAD

**Issue by Qwindrix** [lllyasviel/ControlNet#596]
Hi

I love ControlNet but unfortunately not all models work with ControlNet.
It would be nice to have an warning message when I activate CN while have a specific model loaded.
I understand that you do not want to keep track of which model/version that works or not but why not let us have a local check list?

When a model fails to work with CN, then it will be added to a local text file for future reference.
Next time I activate CN with that model I will get an warning.

Optional feature:
In settings, have a button that scans all models to check if they work or not and store it the the text file.

I'm finding these in my console window now and then: (I'm aware that this is a recolor model that does not work with the selected model but this could also be added to the text file and give a warning next time)

Exception: ControlNet model sai_xl_recolor_256lora [43f2f36a](StableDiffusionVersion.SDXL) is not compatible with sd model(StableDiffusionVersion.SD1x)

**Comment by geroldmeisinger** [comment]
I think it's a good idea and it would already be quite helpful if there is warning for the most popular models. however, the feature request belongs to the controlnet extension projects like https://github.com/Mikubill/sd-webui-controlnet

**Comment by Qwindrix** [comment]
Oops, my bad. You can delete this issue then :)

**Comment by geroldmeisinger** [comment]
oh, I'm just a humble user. you can close it though.
