### ISSUE TITLE
please add xformers and also progress

### ISSUE THREAD

**Issue by FurkanGozukara** [lllyasviel/ControlNet#6]
on RTX 3060 currently testing bird and nothing appears after 200 seconds just gradio error :/

**Comment by FurkanGozukara** [comment]
ye 12 GB vram is not being sufficient currently

definitely needs xformers asap @lllyasviel 
i am making a tutorial video atm :/

**Comment by lllyasviel** [comment]
see if the new low vram mode works

**Comment by FurkanGozukara** [comment]
> see if the new low vram mode works

gonna test right now but please add xformers

**Comment by FurkanGozukara** [comment]
@lllyasviel it worked amazing and speed was great

RTX 3060

**Comment by FurkanGozukara** [comment]
@lllyasviel i have recorded a full tutorial guide video (my channel is https://www.youtube.com/@SEcourses )

how to install run use

however i will be able to post it to my channel hopefully tomorrow. need post production editing

if you can make xformers meanwhile until tomorrow i can also show that

this is a revolution to stable diffusion - this is stable diffusion version 2 :d

**Comment by lllyasviel** [comment]
xformers is difficult to install on windows. but will consider

**Comment by FurkanGozukara** [comment]
> xformers is difficult to install on windows. but will consider

automatic1111 is doing that perhaps you can do same?

**Comment by lllyasviel** [comment]
do they? actually idk how to install xformers for a1111 on windows

**Comment by FurkanGozukara** [comment]
> do they? actually idk how to install xformers for a1111 on windows

Just add - - xformers to command line options

Atuoamfically installed latest version

And in this video I explain how to manually downgrade

I think key is using precompiled wheel or something 

I am not a Unix guy :/

https://youtu.be/O01BrQwOd-Q

**Comment by brycedrennan** [comment]
I'm working on integration with [imaginAIry](https://github.com/brycedrennan/imaginAIry) right now, which I believe, but cannot guarantee will give xformers integration for "free".

**Comment by lllyasviel** [comment]
cool. let me take a look soon

**Comment by xiaoyoucheng** [comment]
```
   if (not is_installed("xformers") or reinstall_xformers) and xformers:
        if platform.system() == "Windows":
            if platform.python_version().startswith("3.10"):
                run_pip(f"install -U -I --no-deps {xformers_package}", "xformers")
            else:
                print("Installation of xformers is not supported in this version of Python.")
                print("You can also check this and build manually: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Xformers#building-xformers-on-windows-by-duckness")
                if not is_installed("xformers"):
                    exit(0)
        elif platform.system() == "Linux":
            run_pip(f"install {xformers_package}", "xformers")
```
This piece of code is from  [stable-diffusion-webui/launch.py](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/ea9bd9fc7409109adcd61b897abc2c8881161256/launch.py) 

>(RECOMMENDED, linux & win)
 Install latest stable with pip: Requires [PyTorch 1.13.1](https://pytorch.org/get-started/locally/)
pip install -U xformers

This part of the document is from [xformers](https://github.com/facebookresearch/xformers)

Based on the information above, I think that xformers can be installed directly on windows systems as long as certain requirements are met.

**Comment by lllyasviel** [comment]
but we use python 3.8.5 right now. perhaps we can evaluate it a bit

**Comment by FurkanGozukara** [comment]
> but we use python 3.8.5 right now. perhaps we can evaluate it a bit

Yes it is depended on many things

By the way your speed improvement was great good job

Batch size and random seed more important atm

I did setup mouse macro to generate different images with different seed :)
