### ISSUE TITLE
Compatibility of ControlNet as a Plugin with Other Drawing Models

### ISSUE THREAD

**Issue by Boomprogrammar** [lllyasviel/ControlNet#606]
First of all, I would like to express my gratitude for the incredible work put into developing the ControlNet plugin. 
I would like to inquire about the compatibility of ControlNet as a plugin with other drawing models. Can ControlNet be used in different open-source drawing models?

**Comment by geroldmeisinger** [comment]
what do you mean with drawing model?

**Comment by Boomprogrammar** [comment]
Sorry, my description was wrong, it should be image generation models like DALL-E
