### ISSUE TITLE
Report an error when unsing Uniformer Segmentation

### ISSUE THREAD

**Issue by tsound97** [lllyasviel/ControlNet#61]
**Python version:** 3.10
**MMCV version:** 1.7.1
**System:** windows 10
**Error content:**
File "A:\ControlNet-main\annotator\uniformer\mmcv\utils\ext_loader.py", line 15, in load_ext assert hasattr(ext, fun), f'{fun} miss in module {name}' AssertionError: top_pool_forward miss in module _ext

**Comment by oylz** [comment]
* you should uninstall system mmcv
```
pip uninstall mmcv -y
```
* the reason is: uniformer using it's self mmcv, there is a conflict

**Comment by tsound97** [comment]
Thx for help! :)


> ## 1.the reason
> * uniformer using it's self mmcv, there is a conflict
> 
> ## 2.the first fix method is
> * you should uninstall system mmcv
> 
> ```
> pip uninstall mmcv -y
> ```
> 
> ## 3.or if you are in linux, the second fix method can be like this
> ```
> export PYTHONPATH=/xxx/controlnet/annotator/uniformer
> ```

**Comment by soysanti** [comment]
and 
pip uninstall openmim -y

**Comment by ntrpnr** [comment]
I don't have mmcv or mmcv-full installed. Not in myenv or elsewhere. Still getting the error.

**Comment by yunghoy** [comment]
I do not have mmcv nor mmcv-full installed as well in venv or even outside of venv. Still getting the error
ControlNet version: 48fce60f (Thu Mar 2 12:55:12 2023)
