### ISSUE TITLE
Path of trained weights using control net

### ISSUE THREAD

**Issue by SaailN** [lllyasviel/ControlNet#639]
After training on custom data where will be the trained weights file(.pth) be saved?
I trained for 10 epoch and killed the training script. Will the weights file be saved ?

**Comment by SaailN** [comment]
Got it, Weights file will be saved in lightning_logs directory. It would be great if the training on custom dataset documentation is improved.

**Comment by WHUEugene** [comment]
pth文件在哪里？
我只找到了ckpt文件
