### ISSUE TITLE
save checkpoint

### ISSUE THREAD

**Issue by gguang10** [lllyasviel/ControlNet#664]
when I use tutorial_train.py to train my own dataset, I notice that the checkpoint folder is empty, and hparams.yaml is {}, the code save a version_x every 300 steps, is the checkpoint folder empty because I haven't trained an epoch yet?
![screenshot](https://github.com/lllyasviel/ControlNet/assets/49913016/e7de1202-eaac-46d3-bc10-3e867f753ece)

**Comment by ziqin-h** [comment]
> when I use tutorial_train.py to train my own dataset, I notice that the checkpoint folder is empty, and hparams.yaml is {}, the code save a version_x every 300 steps, is the checkpoint folder empty because I haven't trained an epoch yet? ![screenshot](https://private-user-images.githubusercontent.com/49913016/316821625-e7de1202-eaac-46d3-bc10-3e867f753ece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3Nzk0NDIsIm5iZiI6MTczMjc3OTE0MiwicGF0aCI6Ii80OTkxMzAxNi8zMTY4MjE2MjUtZTdkZTEyMDItZWFhYy00NmQzLWJjMTAtM2U4NjdmNzUzZWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA3MzIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZGE0NjczMzg2NjhmZWU4YTVhMTlkMjdmNzdmZmUyMGZmZGVjNjJmMDlhZTRhYTYzMjkzNDgyOGI5NWNkM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t1fhuGZrsV3mLnmG_E4n6B9aCFn3XVwDkOL_v9nYxlo)

I have the same problem, can you tell me how did you solve it?

**Comment by gguang10** [comment]
> > when I use tutorial_train.py to train my own dataset, I notice that the checkpoint folder is empty, and hparams.yaml is {}, the code save a version_x every 300 steps, is the checkpoint folder empty because I haven't trained an epoch yet? ![screenshot](https://private-user-images.githubusercontent.com/49913016/316821625-e7de1202-eaac-46d3-bc10-3e867f753ece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3Nzk0NDIsIm5iZiI6MTczMjc3OTE0MiwicGF0aCI6Ii80OTkxMzAxNi8zMTY4MjE2MjUtZTdkZTEyMDItZWFhYy00NmQzLWJjMTAtM2U4NjdmNzUzZWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA3MzIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZGE0NjczMzg2NjhmZWU4YTVhMTlkMjdmNzdmZmUyMGZmZGVjNjJmMDlhZTRhYTYzMjkzNDgyOGI5NWNkM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t1fhuGZrsV3mLnmG_E4n6B9aCFn3XVwDkOL_v9nYxlo)
> 
> I have the same problem, can you tell me how did you solve it?

 I just continued training and when finished, I found the ckpt file in the last version_xx folder.
