### ISSUE TITLE
Help w/ debugging Issues with Scribbles

### ISSUE THREAD

**Issue by dhavalshreyas** [lllyasviel/ControlNet#67]
I've not been able to get high quality results using `scribble2image`. Any ideas on where I should look?

Model: `control_sd15_scribble.pth`
Sampler: DDIM, Steps: 30
Resolution: 512
Prompt: `photo of an owl`

![WhatsApp Image 2023-02-15 at 8 49 16 AM](https://user-images.githubusercontent.com/43150592/219218932-8fcf3cf0-173c-4f43-abe7-c3400751562d.jpeg)

**Comment by KaruroChori** [comment]
Hi, I had quite positive experiences so far, and nothing close to the issue you are reporting.
To make the process of reproducing your results it would be better to share the full set of parameters used, including the actual prompt.
Also sharing the original sketch as its own image would help helping you, or potentially isolating bugs in the underlying implementation.

**Comment by dhavalshreyas** [comment]
Thanks @KaruroChori.

I just reviewed everything and I had not setup the parameters correctly. I was using a guidance scale of 1. 🙈

Thanks for your help! I'll close this one now.
