### ISSUE TITLE
How to set random seed?

### ISSUE THREAD

**Issue by FurkanGozukara** [lllyasviel/ControlNet#7]
-1 seed not working :/

**Comment by lllyasviel** [comment]
right now u need to set it every time. some more options will be added later (perhaps)

**Comment by FurkanGozukara** [comment]
> right now u need to set it every time. some more options will be added later (perhaps)

ye but that is really hard to do

with stable diffusion you have to generate hundreds of images

so we need random seed and continue generating infinite times

also generated images should be saved as well

**Comment by scarbain** [comment]
@FurkanGozukara https://github.com/lllyasviel/ControlNet/pull/20 has been merged. You can set -1 as seed now

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara #20 has been merged. You can set -1 as seed now

Awesome thank you
Can you also add infinite generate and save output?
