### ISSUE TITLE
Annotator resolution slider and number input are disabled and locked to 64

### ISSUE THREAD

**Issue by MalOMaw** [lllyasviel/ControlNet#79]
Canny Annotator resolution slider and number input are disabled and locked to 64. Why is that? I have to manually unstuck it

**Comment by lllyasviel** [comment]
It works fine on my side. any screenshots?

**Comment by MalOMaw** [comment]
> It works fine on my side. any screenshots?

https://imgur.com/a/yLmDAss

Here's how it looks. Depth controls (thresholds) are locked too.

What I tried:

Update webui, enable and disable the plugin, delete ui-config.json so it regenerates. Neither of these worked

**Comment by MalOMaw** [comment]
wrong repo :)
